#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# Author: Old Farmer
# Start VM script
import types
import json
import requests
import urllib3
import string
import random
import sys
import os
import time

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

host = '192.168.13.182'


class Vcenter():

    def get_cookies(self):
        url = 'https://' + host + '/rest/com/vmware/cis/session'

        payload = {}
        files = {}
        headers = {
            'Authorization': 'Basic YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2FsOlRjMTIzNDU2Kigp'
            # username/password which use for login VCenter, generated by BASE64, format: username:password.
        }

        response = requests.request("POST", url, headers=headers, verify=False, data=payload, files=files)

        if response.status_code != 200:
            print("获取cookie失败")
            os.exit(1)

        token = response.headers['set-cookie'][0:54]
        return token


    def list_vm(self, token):
        url = 'https://' + host + '/rest/vcenter/vm'
        playload = {}
        headers = {
            'Cookie': token1
        }
        response = requests.request("GET", url, headers=headers, verify=False, data=playload)
        # print("response:", response)
        json_str = json.loads(response.text)
        # print("json_str:", json_str)
        # print(len(json_str))
        for x in range(0, len(json_str['value'])):
            # print("x:", x)
            print("vm:", json_str['value'][x]['name'], "status:", json_str['value'][x]["power_state"])

    def start_vm(self, vm_name, token):
        # print("vm_name:", vm_name)
        url = 'https://' + host + '/rest/vcenter/vm?filter.names.1={}'.format(vm_name)
        # print(url)
        payload = {}
        headers = {
            'Cookie': token
        }
        response = requests.request("GET", url, headers=headers, verify=False, data=payload)
        if len(response.json()['value']) == 0:
           # print("len:", len(response.json))
            print("没有找到vm:{}".format(vm_name))
            # os._exit(1)
            return
        vm_status = response.json()['value'][0]['power_state']
        # print("vm_status:", vm_status)
        vm = response.json()['value'][0]['vm']
        if vm_status != "POWERED_ON":
            pass
        else:
            # print(vm_name)
            print("vm:{} 运行中,无需开机.".format(vm_name))
            # os._exit(1)
            return


        # start vm
        url = 'https://' + host + '/rest/vcenter/vm/{}/power/start'.format(vm)
        payload = {}
        headers = {
            'Cookie': token
        }
        response = requests.request("POST", url, headers=headers, verify=False, data=payload)
        if response.status_code == 200:
            print("vm:{} starting...".format(vm_name))
        # Check vm status after start.
        # print("\n")
        # if vm_status == "POWERED_ON":
            # print("vm:{}已经开机".format(vm_name))

if __name__ == '__main__':
    # print(sys.argv)
    if len(sys.argv) == 1:
        print("参数错误")
        print("脚本使用方法：")
        print("================================================================")
        print("python {} list_vm".format(sys.argv[0]))
        print("python {} start vm_name1 vm_name2 vm_name(n)".format(sys.argv[0]))
        print("================================================================")
        os._exit(1)

    abc = Vcenter()
    token1 = abc.get_cookies()

    if len(sys.argv) == 2 and sys.argv[1] == "list_vm":
        # print("调用:abc.list_vm(token1)")
        abc.list_vm(token1)
        # print("调用:abc.list_vm(token2)")
    # if len(sys.argv) == 3 and sys.argv[1] == "start":
        # abc.start_vm(sys.argv[2], token1)
    if len(sys.argv) >= 3 and sys.argv[1] == "start":
        for vm_name in sys.argv[2:]:
            print(vm_name)
            abc.start_vm(vm_name, token1)

